### ISSUE TITLE
Wrong behaviour on tfm.get.room.objectList

### ISSUE THREAD

**Issue by tocuto** [Seniru/Module-API-TFM#13]
Basically, this line is adding a physic object to tfm.get.room.objectList: https://github.com/Seniru/Module-API-TFM/blob/1a1622a906183877087405c2e606779f6a90b549/src/tfm.lua#L193

The problem here, is that it doesn't happen in transformice. In this table are only inserted shaman objects.

**Comment by Seniru** [comment]
Hi! Thanks for letting me know. Sorry, I have misunderstood the documentation. So, this line should be under `addShamanObject()` instead of `addPhysicObject()`, isn't it?

> Note that this project is still under heavy development. So you can help me if you like 😛

**Comment by Lautenschlager-id** [comment]
Yes, addShamanObject only.

**Comment by Seniru** [comment]
You are welcome to fix this if you like. Please let me know before starting work

**Comment by Seniru** [comment]
Added to TODO list. Will gwt fixed soon

**Comment by Seniru** [comment]
Closed this issue with the commit https://github.com/Seniru/Module-API-TFM/commit/88a26859c8f8f1e9de66dadb3e7e01608e6c4022 . I hope I've implemented it correctly now 🙏
